name = "rpc-proxy"
main = "./src/index.ts"
compatibility_date = "2022-05-03"

[env.stagging]
workers_dev = true
vars = {
  AWS_REGION = "us-east-1"
}

[env.production]
vars = {
  AWS_REGION = "us-east-1"
}