name = "rpc-proxy"
main = "./src/index.ts"
compatibility_date = "2022-05-03"

[env.stagging]
workers_dev = true
[env.stagging.vars]
AWS_REGION = "us-east-1"

[env.production]
[env.production.vars]
AWS_REGION = "us-east-1"