main = "./src/index.ts"
compatibility_date = "2022-05-03"

[env.dev]
name = "rpc-proxy-dev"
[env.dev.vars]
AWS_REGION = "us-east-1"

[env.production]
name = "rpc-proxy"
[env.production.vars]
AWS_REGION = "us-east-1"