name: Build
on:
  push:
    branches:
      - main
    inputs:
      environment:
        default: 'dev'
      name:
        default: 'rpc-proxy-dev'
  repository_dispatch:
  workflow_dispatch:
    inputs:
      environment:
        default: 'production'
      name:
        default: 'rpc-proxy'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ github.event.environment }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}