name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    env:
      environment: dev
      name: rpc-proxy-dev
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Environment vars
        run: |
          echo "Name: $NAME"
          echo "Environment: $ENVIRONMENT"
        env:
          NAME: ${{ env.name }}
          ENVIRONMENT: ${{ env.environment }}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ env.environment }} --name ${{ env.name }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  production:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      environment: production
      name: rpc-proxy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
      - name: Environment vars
        run: |
          echo "Name: $NAME"
          echo "Environment: $ENVIRONMENT"
        env:
          NAME: ${{ inputs.name }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ inputs.environment }} --name ${{ inputs.name }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}